$(document).ready(function(){
    $(".subnav-1").mouseover(function(){
        $(".subnav_article-1").slideDown(500);
    });
    $(".subnav-1").mouseleave(function(){
        $(".subnav_article-1").slideUp(200);
    });
    $(".subnav-2").mouseover(function(){
        $(".subnav_article-2").slideDown(500);
    });
    $(".subnav-2").mouseleave(function(){
        $(".subnav_article-2").slideUp(200);
    });
    $(".subnav-3").mouseover(function(){
        $(".subnav_article-3").slideDown(500);
    });
    $(".subnav-3").mouseleave(function(){
        $(".subnav_article-3").slideUp(200);
    });
    $(".subnav-4").mouseover(function(){
        $(".subnav_article-4").slideDown(500);
    });
    $(".subnav-4").mouseleave(function(){
        $(".subnav_article-4").slideUp(200);
    });
    $(".subnav-5").mouseover(function(){
        $(".subnav_article-5").slideDown(500);
    });
    $(".subnav-5").mouseleave(function(){
        $(".subnav_article-5").slideUp(200);
    });
    $(".subnav-6").mouseover(function(){
        $(".subnav_article-6").slideDown(500);
    });
    $(".subnav-6").mouseleave(function(){
        $(".subnav_article-6").slideUp(200);
    });
    
  });